ignored = ["github.com/joshdk/licensor/spdxgen"]

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "github.com/joshdk/licensor"
  version = "0.1.0"

[prune]
  go-tests = true
  unused-packages = true
